# Generated by Django 5.2.16 on 2026-07-17 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro')], max_length=3)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_created', to=settings.AUTH_USER_MODEL)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_paid', to='members.member')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='groups.group')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_received', to='members.member')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
