# Generated by Django 5.2.16 on 2026-07-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro')], max_length=3)),
                ('quote', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro')], max_length=3)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('as_of', models.DateField(db_index=True)),
                ('source', models.CharField(default='frankfurter', max_length=32)),
            ],
            options={
                'indexes': [models.Index(fields=['base', 'quote', 'as_of'], name='core_dailyf_base_c45a34_idx')],
                'constraints': [models.UniqueConstraint(fields=('base', 'quote', 'as_of'), name='uniq_fx_pair_per_day')],
            },
        ),
    ]
