# Generated by Django 5.2.16 on 2026-07-17 20:02

import apps.core.encryption
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=150)),
                ('issuer', models.CharField(blank=True, max_length=100)),
                ('network', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('rupay', 'RuPay'), ('amex', 'American Express'), ('other', 'Other')], default='other', max_length=16)),
                ('billing_cycle_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last4_enc', apps.core.encryption.EncryptedCharField(blank=True, null=True)),
                ('expiry_enc', apps.core.encryption.EncryptedCharField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='groups.group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='members.member')),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='CashbackProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.CharField(default='ANY', max_length=120)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='INR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('max_per_txn', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cap_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cap_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cap_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cap_per_year', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cap_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('max_vouches_total', models.PositiveIntegerField(blank=True, null=True)),
                ('max_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('max_per_week', models.PositiveIntegerField(blank=True, null=True)),
                ('max_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('max_per_year', models.PositiveIntegerField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='cards.creditcard')),
            ],
            options={
                'ordering': ['-percent'],
            },
        ),
        migrations.AddIndex(
            model_name='creditcard',
            index=models.Index(fields=['group', 'is_active'], name='cards_credi_group_i_4d627b_idx'),
        ),
        migrations.AddIndex(
            model_name='cashbackprogram',
            index=models.Index(fields=['card', 'is_active'], name='cards_cashb_card_id_7011b9_idx'),
        ),
    ]
