# Generated by Django 5.2.16 on 2026-07-17 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('groups', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro')], max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fx_rate', models.DecimalField(decimal_places=10, default=1, max_digits=20)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('date', models.DateField()),
                ('merchant', models.CharField(blank=True, max_length=120)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('other', 'Other')], default='cash', max_length=16)),
                ('cashback_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('simplify_override', models.BooleanField(default=False)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='cards.creditcard')),
                ('cashback_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='cards.cashbackprogram')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='groups.group')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='expenses.expense')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashbackAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro')], max_length=3)),
                ('accrued_on', models.DateField(db_index=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accruals', to='cards.creditcard')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accruals', to='cards.cashbackprogram')),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accrual', to='expenses.expense')),
            ],
        ),
        migrations.CreateModel(
            name='ExpensePayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=18)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payers', to='expenses.expense')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paid_for', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('split_type', models.CharField(choices=[('equal', 'Equal'), ('exact', 'Exact'), ('percent', 'Percent')], default='equal', max_length=16)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='expenses.expense')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owes_for', to='members.member')),
            ],
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['group', 'date'], name='expenses_ex_group_i_f6bb8c_idx'),
        ),
        migrations.AddIndex(
            model_name='cashbackaccrual',
            index=models.Index(fields=['program', 'accrued_on'], name='expenses_ca_program_c98307_idx'),
        ),
        migrations.AddConstraint(
            model_name='expensepayer',
            constraint=models.UniqueConstraint(fields=('expense', 'member'), name='uniq_expense_payer'),
        ),
        migrations.AddConstraint(
            model_name='expensesplit',
            constraint=models.UniqueConstraint(fields=('expense', 'member'), name='uniq_expense_split'),
        ),
    ]
