# Generated by Django 5.2.16 on 2026-07-17 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cashbackprogram_coin_expiry_days_and_more'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('splitwise_names', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.category'),
        ),
        migrations.CreateModel(
            name='CoinAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coins', models.DecimalField(decimal_places=4, max_digits=18)),
                ('rate_at_award', models.DecimalField(decimal_places=6, max_digits=18)),
                ('cash_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro')], max_length=3)),
                ('awarded_on', models.DateField(db_index=True)),
                ('expires_on', models.DateField(blank=True, db_index=True, null=True)),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coin_accrual', to='expenses.expense')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_accruals', to='cards.cashbackprogram')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accruals', to='cards.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['wallet', 'expires_on'], name='expenses_co_wallet__6e0378_idx')],
            },
        ),
    ]
